esphome:
  name: ha-weather
  friendly_name: ha_weather

external_components:
  - source:
      type: local
      path: common_components/ha_weather

esp32:
  board: esp32dev
  framework:
    type: arduino

# UART bus used by Makerfabs PM2.5 sensor. Update rx_pin/tx_pin to match your wiring if needed.
uart:
  - id: makerfabs_uart
    rx_pin: GPIO16
    tx_pin: GPIO17
    baud_rate: 9600

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XFB8BOHYUWJIPMDUTOiFrVUIFpTj3dwitLuwMCnhy3U="

ota:
  - platform: esphome
    password: "4bd8d398ff9f3b6559b89d6280451bb5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ha-Weather Fallback Hotspot"
    password: "nFY2nMgi9izu"

captive_portal:



i2c:
  - id: i2c1
    sda: GPIO4
    scl: GPIO5
    scan: True
sensor:
  - platform: makerfabs_pm25
    name: "Makerfabs PM2.5 Sensor"
    uart_id: makerfabs_uart

  - platform: aht10
    temperature:
      name: "Makerfabs Temperature"
    humidity:
      name: "Makerfabs Humidity"
    update_interval: 10s

  - platform: pulse_counter
    pin: 27
    name: "Wind Speed"
    unit_of_measurement: 'm/s'
    filters:
      - multiply: 0.002

  - platform: bmp280_i2c
    pressure:
      name: "Outside Pressure"
    address: 0x76
    update_interval: 10s






