esphome:
  name: rgb565
  friendly_name: Matouch ESP32_S3 RGB565

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
      CONFIG_COMPILER_OPTIMIZATION_PERF: y
      CONFIG_FREERTOS_UNICORE: n
      CONFIG_FREERTOS_TIMER_TASK_STACK_DEPTH: "4096"
      CONFIG_FREERTOS_TASK_NOTIFICATION_ARRAY_ENTRIES: "3"
      CONFIG_ESPTOOLPY_FLASHSIZE_16MB: y 

psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger:
  level: DEBUG
# Enable Home Assistant API
api:
  encryption:
    key: "5DQ0UsfBrLmofn2GjgWwrlGGbaa81g22Y+dfiQYff3I="

ota:
  - platform: esphome
    password: "f92b6f28ac0f9f6471d5c881d1ea594d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rgb565 Fallback Hotspot"
    password: "F03ZsTI6ltRE"

captive_portal:

i2c:
  - id: touch_i2c
    sda: GPIO17
    scl: GPIO18
    scan: True




display:
  - platform: rpi_dpi_rgb
    id: rgb_display
    color_order: RGB
    pclk_frequency: 16MHz
    dimensions:
      width: 1024
      height: 600
    de_pin: 40
    hsync_pin: 39
    vsync_pin: 41
    pclk_pin: 42
    hsync_back_porch: 128
    hsync_front_porch: 40
    hsync_pulse_width: 48
    vsync_back_porch: 45
    vsync_front_porch: 13
    vsync_pulse_width: 3
    data_pins:
      red:
        - 45        #r1
        - 48        #r2
        - 47        #r3
        - 21        #r4
        - 14        #r5
      green:
        - 5         #g0
        - 6         #g1
        - 7         #g2
        - 15        #g3
        - 16        #g4
        - 4         #g5
      blue:
        - 8         #b1
        - 3         #b2
        - 46        #b3
        - 9         #b4
        - 1         #b5

touchscreen:
  - platform: gt911
    display: rgb_display
    id: touch_screen
    update_interval: 16ms
    i2c_id: touch_i2c
    transform:
      swap_xy: False
      mirror_x: False
      mirror_y: False

lvgl:

            